name: CI/CD Pipeline for Node API and MongoDB

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Docker Compose (fix for "command not found" issue)
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose-plugin

      # Step 4: Log in to DockerHub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 5: Build and Push Docker images using docker-compose
      - name: Build and Push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      # Step 6: Log out from DockerHub
      - name: Log out from DockerHub
        run: docker logout
